name: Build and Test PySpark Jupyter Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyspark
        pip install jupyter
        pip install nbmake
        pip install flake8
        pip install pytest-cov
        pip install black
        pip install isort
        pip install bandit
        pip install "black[jupyter]"
    
    - name: Run static code analysis
      run: |
        flake8 .
        black --check .
        isort --check-only .
    - name: Run security scan
      run: |
        bandit -r *.ipynb

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace installrequirements.ipynb
        jupyter nbconvert --to notebook --execute --inplace reuseGenerateData.ipynb
        jupyter nbconvert --to notebook --execute --inplace main.ipynb
        jupyter nbconvert --to notebook --execute --inplace initializespark.ipynb
        jupyter nbconvert --to notebook --execute --inplace healthdataanalysis.ipynb
        

    - name: Run tests
      run: |
        pytest --nbmake --cov=./ --cov-report=xml --cov-report=term tests/

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          main.ipynb
          installrequirements.ipynb
          initializespark.ipynb
          healthdataanalysis.ipynb
          installrequirements.ipynb
